2024-02-22 23:46:18,434 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 23:46:18,434 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 23:46:18,434 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 23:46:18,434 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 23:46:18,444 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 23:46:18,444 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 23:46:18,444 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 23:46:18,444 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 23:46:18,444 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 23:46:20,529 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 23:46:20,529 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 23:46:20,529 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 23:46:22,133 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 23:46:22,134 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 23:46:22,134 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 23:46:22,141 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 23:46:22,141 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 23:46:22,141 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 23:46:22,141 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 23:46:22,141 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 23:46:22,141 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 23:46:22,141 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 23:46:22,141 - INFO - [96mAttempting to create database:[0m
2024-02-22 23:46:22,142 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 23:46:22,142 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 23:46:22,142 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 23:46:22,142 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 23:46:22,142 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 23:46:22,142 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 23:46:22,143 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 23:46:22,193 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 23:46:22,193 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 23:46:22,193 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 23:46:22,209 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 23:46:22,209 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 23:46:22,209 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 23:46:22,209 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:46:22,209 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 23:46:22,209 - INFO - [94mAttempting to add following line:[0m
2024-02-22 23:46:22,209 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:46:22,209 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 23:46:22,209 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-22 23:46:22,209 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 23:46:22,209 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 23:46:22,209 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 23:46:28,604 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 23:46:28,604 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 23:46:28,604 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 23:46:28,619 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 23:46:28,619 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 23:46:28,619 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 23:46:28,619 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:46:28,708 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 23:46:28,708 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 23:46:28,708 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 23:46:28,708 - INFO - [94mVerifying schema creation...[0m
2024-02-22 23:46:28,743 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-22 23:46:28,777 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-22 23:46:28,815 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-22 23:46:28,852 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-22 23:46:28,853 - INFO - [92mAll schemas created successfully! Logging layout of created schemas...[0m
2024-02-22 23:46:28,853 - ERROR - db_layout_visual.txt not found.
2024-02-22 23:49:55,978 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 23:49:55,978 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 23:49:55,978 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 23:49:55,978 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 23:49:55,988 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 23:49:55,988 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 23:49:55,988 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 23:49:55,988 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 23:49:55,988 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 23:49:59,363 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 23:49:59,363 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 23:49:59,363 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 23:50:00,783 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 23:50:00,783 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 23:50:00,783 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 23:50:00,791 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 23:50:00,791 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 23:50:00,791 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 23:50:00,791 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 23:50:00,791 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 23:50:00,791 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 23:50:00,791 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 23:50:00,791 - INFO - [96mAttempting to create database:[0m
2024-02-22 23:50:00,791 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 23:50:00,791 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 23:50:00,792 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 23:50:00,792 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 23:50:00,792 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 23:50:00,793 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 23:50:00,793 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 23:50:00,820 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 23:50:00,820 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 23:50:00,820 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 23:50:00,835 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 23:50:00,835 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 23:50:00,836 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 23:50:00,836 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:50:00,836 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 23:50:00,836 - INFO - [94mAttempting to add following line:[0m
2024-02-22 23:50:00,836 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:50:00,836 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 23:50:00,836 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-22 23:50:00,836 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 23:50:00,836 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 23:50:00,836 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 23:50:07,213 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 23:50:07,213 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 23:50:07,213 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 23:50:07,229 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 23:50:07,229 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 23:50:07,230 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 23:50:07,230 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 23:50:07,277 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 23:50:07,277 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 23:50:07,277 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 23:50:07,277 - INFO - [94mVerifying schema creation...[0m
2024-02-22 23:50:07,312 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-22 23:50:07,346 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-22 23:50:07,381 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-22 23:50:07,414 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-22 23:50:07,414 - INFO - [92mAll schemas created successfully! Logging layout of created schemas...[0m
2024-02-22 23:50:07,418 - INFO - [94mLayout of created schemas::[0m
2024-02-22 23:50:07,418 - INFO - [93m
# project_google_horeca_reviews                                                            (NAME DATABASE)
# │
# ├── horca_parameters_client                                                              (NAME SCHEMA)
# │   └── client_data
# │       ├── client_name (TXT)                                                                      (NAME TABLE)
# │       ├── client_id (SERIAL)                                                           (NAME ID)
# │       ├── client_data (JSONB)                                                          (NAME DATA)
# │       └── created_at (TIMESTAMP)                                                       (NAME TIME-CREATED)
# │
# ├── google_account_info
# │   └── account_data
# │       ├── account_id (SERIAL)
# │       ├── account_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# ├── standard_strings_review
# │   └── standard_string
# │       ├── string_id (SERIAL)
# │       ├── string_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# │
# │
# └── created_horeca_reviews
#     └── reviews_data
#         ├── client_name (TXT)
#         ├── review_id (SERIAL)
#         ├── review_data (JSONB)
#         └── created_at (TIMESTAMP)
#         └── review_count (INTEGER)
[0m
2024-02-23 00:22:23,042 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 00:22:23,042 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 00:22:23,042 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 00:22:23,042 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 00:22:23,052 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 00:22:23,052 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 00:22:23,052 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 00:22:23,052 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:22:23,052 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 00:22:25,279 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 00:22:25,280 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 00:22:25,280 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:22:26,678 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 00:22:26,678 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 00:22:26,679 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 00:22:26,686 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 00:22:26,686 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 00:22:26,686 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 00:22:26,686 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 00:22:26,686 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 00:22:26,687 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 00:22:26,687 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 00:22:26,687 - INFO - [96mAttempting to create database:[0m
2024-02-23 00:22:26,687 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:22:26,687 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 00:22:26,687 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 00:22:26,687 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:22:26,688 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 00:22:26,688 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:22:26,688 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 00:22:26,720 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 00:22:26,720 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:22:26,720 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:22:26,737 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:22:26,737 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 00:22:26,737 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 00:22:26,738 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:22:26,738 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 00:22:26,738 - INFO - [94mAttempting to add following line:[0m
2024-02-23 00:22:26,738 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:22:26,738 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 00:22:26,738 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 00:22:26,738 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 00:22:26,738 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:22:26,738 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 00:22:33,129 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 00:22:33,129 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:22:33,129 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:22:33,147 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:22:33,147 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 00:22:33,147 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 00:22:33,147 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:22:33,195 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 00:22:33,195 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 00:22:33,195 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 00:22:33,195 - INFO - [94mVerifying schema creation...[0m
2024-02-23 00:22:33,230 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 00:22:33,263 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 00:22:33,299 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 00:22:33,339 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 00:22:33,339 - INFO - [92mAll schemas created successfully![0m
2024-02-23 00:22:33,339 - INFO - [96mCalling[0m[93m verify_table_schema_is_present_and_correct.py[0m [96mservice -function[0m
2024-02-23 00:22:33,339 - ERROR - [91mError: verify_table_schema_is_present_and_correct() missing 2 required positional arguments: 'init_db_script' and 'schemas'[0m
2024-02-23 00:25:58,949 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 00:25:58,949 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 00:25:58,949 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 00:25:58,949 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 00:25:58,958 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 00:25:58,958 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 00:25:58,958 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 00:25:58,959 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:25:58,959 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 00:26:01,149 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 00:26:01,149 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 00:26:01,149 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:26:02,288 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 00:26:02,288 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 00:26:02,288 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 00:26:02,296 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 00:26:02,296 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 00:26:02,296 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 00:26:02,296 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 00:26:02,296 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 00:26:02,296 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 00:26:02,296 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 00:26:02,296 - INFO - [96mAttempting to create database:[0m
2024-02-23 00:26:02,296 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:26:02,297 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 00:26:02,297 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 00:26:02,297 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:26:02,297 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 00:26:02,298 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:26:02,298 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 00:26:02,345 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 00:26:02,345 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:26:02,345 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:26:02,363 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:26:02,363 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 00:26:02,363 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 00:26:02,363 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:26:02,363 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 00:26:02,363 - INFO - [94mAttempting to add following line:[0m
2024-02-23 00:26:02,363 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:26:02,363 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 00:26:02,363 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 00:26:02,363 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 00:26:02,363 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:26:02,363 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 00:26:08,753 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 00:26:08,753 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:26:08,753 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:26:08,771 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:26:08,771 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 00:26:08,771 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 00:26:08,771 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:26:08,823 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 00:26:08,823 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 00:26:08,823 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 00:26:08,823 - INFO - [94mVerifying schema creation...[0m
2024-02-23 00:26:08,858 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 00:26:08,894 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 00:26:08,930 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 00:26:08,966 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 00:26:08,966 - INFO - [92mAll schemas created successfully![0m
2024-02-23 00:26:08,966 - INFO - [96mCalling[0m[93m verify_table_schema_is_present_and_correct.py[0m [96mservice -function[0m
2024-02-23 00:26:08,966 - INFO - [94mChecking if tables from './config/init-db.psql' exist in specified schemas:[0m
2024-02-23 00:26:08,966 - INFO - [96mhorca_parameters_client[0m
2024-02-23 00:26:08,966 - INFO - [96mgoogle_account_info[0m
2024-02-23 00:26:08,966 - INFO - [96mstandard_strings_review[0m
2024-02-23 00:26:08,966 - INFO - [96mcreated_horeca_reviews[0m
2024-02-23 00:26:08,966 - INFO - [96mSchema: [95mcreated_horeca_reviews[0m
2024-02-23 00:26:08,966 - INFO - [93mTable: [92mcreated_horeca_reviews.[0m
2024-02-23 00:26:09,002 - ERROR - [91mTable '' does not exist in schema 'created_horeca_reviews'[0m
2024-02-23 00:26:09,002 - INFO - [96mSchema: [95mstandard_strings_review[0m
2024-02-23 00:26:09,006 - INFO - [93mTable: [92mstandard_strings_review.[0m
2024-02-23 00:26:09,045 - ERROR - [91mTable '' does not exist in schema 'standard_strings_review'[0m
2024-02-23 00:26:09,045 - INFO - [96mSchema: [95mgoogle_account_info[0m
2024-02-23 00:26:09,046 - INFO - [93mTable: [92mgoogle_account_info.[0m
2024-02-23 00:26:09,081 - ERROR - [91mTable '' does not exist in schema 'google_account_info'[0m
2024-02-23 00:26:09,081 - INFO - [96mSchema: [95mhorca_parameters_client[0m
2024-02-23 00:26:09,081 - INFO - [93mTable: [92mhorca_parameters_client.[0m
2024-02-23 00:26:09,117 - ERROR - [91mTable '' does not exist in schema 'horca_parameters_client'[0m
2024-02-23 00:30:04,618 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 00:30:04,618 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 00:30:04,618 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 00:30:04,618 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 00:30:04,628 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 00:30:04,628 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 00:30:04,628 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 00:30:04,628 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:30:04,628 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 00:30:06,656 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 00:30:06,656 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 00:30:06,656 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:30:07,772 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 00:30:07,772 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 00:30:07,772 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 00:30:07,780 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 00:30:07,780 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 00:30:07,781 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 00:30:07,781 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 00:30:07,781 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 00:30:07,781 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 00:30:07,781 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 00:30:07,781 - INFO - [96mAttempting to create database:[0m
2024-02-23 00:30:07,781 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:30:07,781 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 00:30:07,781 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 00:30:07,781 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:30:07,782 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 00:30:07,782 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:30:07,782 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 00:30:07,825 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 00:30:07,825 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:30:07,825 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:30:07,843 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:30:07,843 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 00:30:07,843 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 00:30:07,843 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:30:07,843 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 00:30:07,843 - INFO - [94mAttempting to add following line:[0m
2024-02-23 00:30:07,843 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:30:07,843 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 00:30:07,843 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 00:30:07,843 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 00:30:07,843 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:30:07,843 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 00:30:14,205 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 00:30:14,205 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:30:14,205 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:30:14,223 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:30:14,223 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 00:30:14,223 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 00:30:14,223 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:30:14,272 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 00:30:14,272 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 00:30:14,272 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 00:30:14,272 - INFO - [94mVerifying schema creation...[0m
2024-02-23 00:30:14,308 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 00:30:14,347 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 00:30:14,385 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 00:30:14,419 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 00:30:14,419 - INFO - [92mAll schemas created successfully![0m
2024-02-23 00:30:14,419 - INFO - [96mCalling[0m[93m verify_table_schema_is_present_and_correct.py[0m [96mservice -function[0m
2024-02-23 00:30:14,419 - INFO - [94mChecking if tables from './config/init-db.psql' exist in specified schemas:[0m
2024-02-23 00:30:14,419 - INFO - [96mhorca_parameters_client[0m
2024-02-23 00:30:14,419 - INFO - [96mgoogle_account_info[0m
2024-02-23 00:30:14,419 - INFO - [96mstandard_strings_review[0m
2024-02-23 00:30:14,419 - INFO - [96mcreated_horeca_reviews[0m
2024-02-23 00:30:14,419 - INFO - [96mSchema: [95mgoogle_account_info[0m
2024-02-23 00:30:14,419 - INFO - [93mTable: [92mgoogle_account_info.IF[0m
2024-02-23 00:30:14,454 - ERROR - [91mTable 'IF' does not exist in schema 'google_account_info'[0m
2024-02-23 00:30:14,454 - INFO - [96mSchema: [95mstandard_strings_review[0m
2024-02-23 00:30:14,454 - INFO - [93mTable: [92mstandard_strings_review.IF[0m
2024-02-23 00:30:14,488 - ERROR - [91mTable 'IF' does not exist in schema 'standard_strings_review'[0m
2024-02-23 00:30:14,489 - INFO - [96mSchema: [95mcreated_horeca_reviews[0m
2024-02-23 00:30:14,489 - INFO - [93mTable: [92mcreated_horeca_reviews.IF[0m
2024-02-23 00:30:14,524 - ERROR - [91mTable 'IF' does not exist in schema 'created_horeca_reviews'[0m
2024-02-23 00:30:14,524 - INFO - [96mSchema: [95mhorca_parameters_client[0m
2024-02-23 00:30:14,524 - INFO - [93mTable: [92mhorca_parameters_client.IF[0m
2024-02-23 00:30:14,559 - ERROR - [91mTable 'IF' does not exist in schema 'horca_parameters_client'[0m
2024-02-23 00:31:09,063 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 00:31:09,063 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 00:31:09,063 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 00:31:09,063 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 00:31:09,072 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 00:31:09,072 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 00:31:09,072 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 00:31:09,072 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:31:09,073 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 00:31:12,988 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 00:31:12,988 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 00:31:12,988 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:31:14,336 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 00:31:14,337 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 00:31:14,337 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 00:31:14,345 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 00:31:14,345 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 00:31:14,345 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 00:31:14,345 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 00:31:14,345 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 00:31:14,345 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 00:31:14,345 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 00:31:14,345 - INFO - [96mAttempting to create database:[0m
2024-02-23 00:31:14,345 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:31:14,345 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 00:31:14,345 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 00:31:14,345 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:31:14,346 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 00:31:14,346 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:31:14,346 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 00:31:14,401 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 00:31:14,401 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:31:14,401 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:31:14,419 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:31:14,419 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 00:31:14,419 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 00:31:14,419 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:31:14,419 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 00:31:14,419 - INFO - [94mAttempting to add following line:[0m
2024-02-23 00:31:14,419 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:31:14,419 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 00:31:14,419 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 00:31:14,419 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 00:31:14,420 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:31:14,420 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 00:31:20,797 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 00:31:20,797 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:31:20,797 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:31:20,815 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:31:20,815 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 00:31:20,815 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 00:31:20,815 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:31:20,863 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 00:31:20,863 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 00:31:20,863 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 00:31:20,863 - INFO - [94mVerifying schema creation...[0m
2024-02-23 00:31:20,898 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 00:31:20,932 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 00:31:20,968 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 00:31:21,005 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 00:31:21,005 - INFO - [92mAll schemas created successfully![0m
2024-02-23 00:31:21,005 - INFO - [96mCalling[0m[93m verify_table_schema_is_present_and_correct.py[0m [96mservice -function[0m
2024-02-23 00:31:21,005 - INFO - [94mChecking if tables from './config/init-db.psql' exist in specified schemas:[0m
2024-02-23 00:31:21,005 - INFO - [96mhorca_parameters_client[0m
2024-02-23 00:31:21,005 - INFO - [96mgoogle_account_info[0m
2024-02-23 00:31:21,005 - INFO - [96mstandard_strings_review[0m
2024-02-23 00:31:21,005 - INFO - [96mcreated_horeca_reviews[0m
2024-02-23 00:31:21,005 - INFO - [96mSchema: [95mhorca_parameters_client[0m
2024-02-23 00:31:21,005 - INFO - [93mTable: [92mhorca_parameters_client.NOT[0m
2024-02-23 00:31:21,042 - ERROR - [91mTable 'NOT' does not exist in schema 'horca_parameters_client'[0m
2024-02-23 00:31:21,042 - INFO - [96mSchema: [95mgoogle_account_info[0m
2024-02-23 00:31:21,042 - INFO - [93mTable: [92mgoogle_account_info.NOT[0m
2024-02-23 00:31:21,080 - ERROR - [91mTable 'NOT' does not exist in schema 'google_account_info'[0m
2024-02-23 00:31:21,080 - INFO - [96mSchema: [95mcreated_horeca_reviews[0m
2024-02-23 00:31:21,080 - INFO - [93mTable: [92mcreated_horeca_reviews.NOT[0m
2024-02-23 00:31:21,114 - ERROR - [91mTable 'NOT' does not exist in schema 'created_horeca_reviews'[0m
2024-02-23 00:31:21,114 - INFO - [96mSchema: [95mstandard_strings_review[0m
2024-02-23 00:31:21,114 - INFO - [93mTable: [92mstandard_strings_review.NOT[0m
2024-02-23 00:31:21,149 - ERROR - [91mTable 'NOT' does not exist in schema 'standard_strings_review'[0m
2024-02-23 00:33:01,775 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 00:33:01,775 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 00:33:01,775 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 00:33:01,775 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 00:33:01,784 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 00:33:01,784 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 00:33:01,784 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 00:33:01,784 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:33:01,784 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 00:33:03,766 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 00:33:03,766 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 00:33:03,766 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 00:33:04,326 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 00:33:04,326 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 00:33:04,326 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 00:33:04,333 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 00:33:04,334 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 00:33:04,334 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 00:33:04,334 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 00:33:04,334 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 00:33:04,334 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 00:33:04,334 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 00:33:04,334 - INFO - [96mAttempting to create database:[0m
2024-02-23 00:33:04,334 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:33:04,334 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 00:33:04,334 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 00:33:04,334 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 00:33:04,335 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 00:33:04,335 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:33:04,335 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 00:33:04,372 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 00:33:04,372 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:33:04,372 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:33:04,390 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:33:04,390 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 00:33:04,390 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 00:33:04,390 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:33:04,390 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 00:33:04,390 - INFO - [94mAttempting to add following line:[0m
2024-02-23 00:33:04,390 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:33:04,390 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 00:33:04,391 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 00:33:04,391 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 00:33:04,391 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 00:33:04,391 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 00:33:10,749 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 00:33:10,749 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 00:33:10,749 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 00:33:10,766 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 00:33:10,767 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 00:33:10,767 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 00:33:10,767 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 00:33:10,817 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 00:33:10,817 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 00:33:10,817 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 00:33:10,817 - INFO - [94mVerifying schema creation...[0m
2024-02-23 00:33:10,855 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 00:33:10,890 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 00:33:10,925 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 00:33:10,961 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 00:33:10,961 - INFO - [92mAll schemas created successfully![0m
2024-02-23 00:33:10,961 - INFO - [96mCalling[0m[93m verify_table_schema_is_present_and_correct.py[0m [96mservice -function[0m
2024-02-23 00:33:10,961 - INFO - [94mChecking if tables from './config/init-db.psql' exist in specified schemas:[0m
2024-02-23 00:33:10,961 - INFO - [96mhorca_parameters_client[0m
2024-02-23 00:33:10,961 - INFO - [96mgoogle_account_info[0m
2024-02-23 00:33:10,961 - INFO - [96mstandard_strings_review[0m
2024-02-23 00:33:10,962 - INFO - [96mcreated_horeca_reviews[0m
2024-02-23 00:33:10,962 - INFO - [96mSchema: [95mcreated_horeca_reviews[0m
2024-02-23 00:33:10,962 - INFO - [93mTable: [92mcreated_horeca_reviews.NOT[0m
2024-02-23 00:33:10,997 - ERROR - [91mTable 'NOT' does not exist in schema 'created_horeca_reviews'[0m
2024-02-23 00:33:10,997 - INFO - [96mSchema: [95mstandard_strings_review[0m
2024-02-23 00:33:10,997 - INFO - [93mTable: [92mstandard_strings_review.NOT[0m
2024-02-23 00:33:11,033 - ERROR - [91mTable 'NOT' does not exist in schema 'standard_strings_review'[0m
2024-02-23 00:33:11,034 - INFO - [96mSchema: [95mgoogle_account_info[0m
2024-02-23 00:33:11,034 - INFO - [93mTable: [92mgoogle_account_info.NOT[0m
2024-02-23 00:33:11,071 - ERROR - [91mTable 'NOT' does not exist in schema 'google_account_info'[0m
2024-02-23 00:33:11,071 - INFO - [96mSchema: [95mhorca_parameters_client[0m
2024-02-23 00:33:11,071 - INFO - [93mTable: [92mhorca_parameters_client.NOT[0m
2024-02-23 00:33:11,107 - ERROR - [91mTable 'NOT' does not exist in schema 'horca_parameters_client'[0m
2024-02-23 01:07:58,506 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 01:07:58,506 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 01:07:58,506 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 01:07:58,506 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 01:07:58,519 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 01:07:58,519 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 01:07:58,519 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 01:07:58,519 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:07:58,519 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 01:08:01,345 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 01:08:01,345 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 01:08:01,345 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:08:03,061 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 01:08:03,061 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 01:08:03,061 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 01:08:03,094 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:08:03,094 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 01:08:03,094 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 01:08:03,094 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 01:08:03,094 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:08:03,094 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:08:03,094 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:08:03,094 - INFO - [96mAttempting to create database:[0m
2024-02-23 01:08:03,094 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:08:03,095 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 01:08:03,095 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 01:08:03,095 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:08:03,100 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 01:08:03,101 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:08:03,101 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 01:08:03,145 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 01:08:03,145 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:08:03,145 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:08:03,162 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:08:03,162 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 01:08:03,162 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 01:08:03,162 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:08:03,162 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 01:08:03,162 - INFO - [94mAttempting to add following line:[0m
2024-02-23 01:08:03,162 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:08:03,162 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 01:08:03,162 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 01:08:03,163 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 01:08:03,163 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:08:03,163 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 01:08:09,669 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 01:08:09,669 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:08:09,670 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:08:09,683 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:08:09,683 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 01:08:09,683 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 01:08:09,683 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:08:09,754 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 01:08:09,754 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string_data (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 01:08:09,754 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 01:08:09,754 - INFO - [94mVerifying schema creation...[0m
2024-02-23 01:08:09,789 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 01:08:09,823 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 01:08:09,858 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 01:08:09,891 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 01:08:09,891 - INFO - [92mAll schemas created successfully![0m
2024-02-23 01:08:09,891 - INFO - [96mCalling[0m[93m verify_permissions_usr_db_granted.py[0m [96mservice -function[0m
2024-02-23 01:08:09,898 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:08:09,898 - INFO - [94mdatabase:[0m[95m        'project_google_reviews'       [0m
2024-02-23 01:08:09,898 - INFO - [94muser:[0m[95m            'project_google_reviews_usr'         [0m
2024-02-23 01:08:09,898 - INFO - [94mpassword:[0m[95m        'Oo51knSSV3OSwfuy8WFu'         [0m
2024-02-23 01:08:09,898 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:08:09,898 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:08:09,898 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:08:09,901 - INFO - [92mAll expected privileges are present in the response.[0m
2024-02-23 01:08:09,901 - INFO - [96m{'TRIGGER', 'UPDATE', 'INSERT', 'TRUNCATE', 'DELETE', 'SELECT', 'REFERENCES'}[0m
2024-02-23 01:14:07,790 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 01:14:07,790 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 01:14:07,790 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 01:14:07,790 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 01:14:07,800 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 01:14:07,800 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 01:14:07,800 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 01:14:07,800 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:14:07,800 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 01:14:10,125 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 01:14:10,125 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 01:14:10,125 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:14:11,325 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 01:14:11,325 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 01:14:11,326 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 01:14:11,334 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:14:11,334 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 01:14:11,334 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 01:14:11,334 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 01:14:11,334 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:14:11,334 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:14:11,334 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:14:11,334 - INFO - [96mAttempting to create database:[0m
2024-02-23 01:14:11,334 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:14:11,334 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 01:14:11,334 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 01:14:11,334 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:14:11,335 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 01:14:11,335 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:14:11,335 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 01:14:11,388 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 01:14:11,388 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:14:11,388 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:14:11,402 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:14:11,403 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 01:14:11,403 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 01:14:11,403 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:14:11,403 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 01:14:11,403 - INFO - [94mAttempting to add following line:[0m
2024-02-23 01:14:11,403 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:14:11,403 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 01:14:11,403 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 01:14:11,403 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 01:14:11,403 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:14:11,403 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 01:14:17,884 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 01:14:17,885 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:14:17,885 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:14:17,910 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:14:17,910 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 01:14:17,910 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 01:14:17,910 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:14:17,963 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 01:14:17,963 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string_data (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 01:14:17,963 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 01:14:17,963 - INFO - [94mVerifying schema creation...[0m
2024-02-23 01:14:17,996 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 01:14:18,031 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 01:14:18,064 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 01:14:18,099 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 01:14:18,099 - INFO - [92mAll schemas created successfully![0m
2024-02-23 01:14:18,099 - INFO - [96mCalling[0m[93m verify_permissions_usr_db_granted.py[0m [96mservice -function[0m
2024-02-23 01:14:18,106 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:14:18,106 - INFO - [94mdatabase:[0m[95m        'project_google_reviews'       [0m
2024-02-23 01:14:18,106 - INFO - [94muser:[0m[95m            'project_google_reviews_usr'         [0m
2024-02-23 01:14:18,106 - INFO - [94mpassword:[0m[95m        'Oo51knSSV3OSwfuy8WFu'         [0m
2024-02-23 01:14:18,106 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:14:18,106 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:14:18,106 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:14:18,109 - INFO - [94mAttempting to check if all expected/needed privileges are granted to:[0m
2024-02-23 01:14:18,109 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 01:14:18,109 - INFO - [96mOn Database:         [95mproject_google_reviews[0m
2024-02-23 01:14:18,109 - INFO - [92mAll expected privileges are present in the response.[0m
2024-02-23 01:14:18,109 - INFO - [96mPermissions:[0m
2024-02-23 01:14:18,109 - INFO - [96mDELETE    [95mAllow to remove rows from a table.[0m
2024-02-23 01:14:18,109 - INFO - [96mINSERT    [95mAllow to add new rows to a table.[0m
2024-02-23 01:14:18,109 - INFO - [96mREFERENCES[95mAllow to create a foreign key constraint.[0m
2024-02-23 01:14:18,109 - INFO - [96mSELECT    [95mAllow to retrieve data from a table.[0m
2024-02-23 01:14:18,109 - INFO - [96mTRIGGER   [95mAllow to create triggers on a table.[0m
2024-02-23 01:14:18,109 - INFO - [96mTRUNCATE  [95mAllow to remove all rows from a table.[0m
2024-02-23 01:14:18,109 - INFO - [96mUPDATE    [95mAllow to modify existing rows in a table.[0m
2024-02-23 01:15:49,946 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-23 01:15:49,946 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-23 01:15:49,946 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-23 01:15:49,946 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-23 01:15:49,957 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-23 01:15:49,957 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-23 01:15:49,957 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-23 01:15:49,957 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:15:49,957 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-23 01:15:52,233 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-23 01:15:52,233 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-23 01:15:52,233 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-23 01:15:53,637 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-23 01:15:53,637 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-23 01:15:53,637 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-23 01:15:53,649 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:15:53,649 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-23 01:15:53,649 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-23 01:15:53,649 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-23 01:15:53,649 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:15:53,649 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:15:53,649 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:15:53,650 - INFO - [96mAttempting to create database:[0m
2024-02-23 01:15:53,650 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:15:53,650 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-23 01:15:53,650 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-23 01:15:53,650 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-23 01:15:53,651 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-23 01:15:53,651 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:15:53,651 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-23 01:15:53,713 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-23 01:15:53,713 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:15:53,713 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:15:53,727 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:15:53,727 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-23 01:15:53,727 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-23 01:15:53,727 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:15:53,727 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 01:15:53,727 - INFO - [94mAttempting to add following line:[0m
2024-02-23 01:15:53,727 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:15:53,727 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-23 01:15:53,727 - INFO - [95mlocal   project_google_reviews   project_google_reviews_usr   tmd5[0m
2024-02-23 01:15:53,727 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-23 01:15:53,727 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-23 01:15:53,728 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-23 01:16:00,273 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-23 01:16:00,274 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-23 01:16:00,277 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-23 01:16:00,297 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-23 01:16:00,297 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-23 01:16:00,297 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-23 01:16:00,297 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-23 01:16:00,352 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-23 01:16:00,352 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_reviews;
You are now connected to database "project_google_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string_data (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-23 01:16:00,352 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-23 01:16:00,352 - INFO - [94mVerifying schema creation...[0m
2024-02-23 01:16:00,392 - INFO - [92mSchema:      [0m[95mhorca_parameters_client[0m[92m verified to be created successfully.[0m
2024-02-23 01:16:00,425 - INFO - [92mSchema:      [0m[95mgoogle_account_info[0m[92m verified to be created successfully.[0m
2024-02-23 01:16:00,458 - INFO - [92mSchema:      [0m[95mstandard_strings_review[0m[92m verified to be created successfully.[0m
2024-02-23 01:16:00,493 - INFO - [92mSchema:      [0m[95mcreated_horeca_reviews[0m[92m verified to be created successfully.[0m
2024-02-23 01:16:00,494 - INFO - [92mAll schemas created successfully![0m
2024-02-23 01:16:00,494 - INFO - [96mCalling[0m[93m verify_permissions_usr_db_granted.py[0m [96mservice -function[0m
2024-02-23 01:16:00,500 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-23 01:16:00,500 - INFO - [94mdatabase:[0m[95m        'project_google_reviews'       [0m
2024-02-23 01:16:00,500 - INFO - [94muser:[0m[95m            'project_google_reviews_usr'         [0m
2024-02-23 01:16:00,500 - INFO - [94mpassword:[0m[95m        'Oo51knSSV3OSwfuy8WFu'         [0m
2024-02-23 01:16:00,500 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-23 01:16:00,500 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-23 01:16:00,500 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-23 01:16:00,503 - INFO - [94mAttempting to check if all expected/needed privileges are granted to:[0m
2024-02-23 01:16:00,503 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-23 01:16:00,503 - INFO - [96mOn Database:         [95mproject_google_reviews[0m
2024-02-23 01:16:00,503 - INFO - [92mAll expected privileges are present in the response.[0m
2024-02-23 01:16:00,503 - INFO - [94mPermissions:[0m
2024-02-23 01:16:00,503 - INFO - [96mDELETE    [95m	Allow to remove rows from a table.[0m
2024-02-23 01:16:00,503 - INFO - [96mINSERT    [95m	Allow to add new rows to a table.[0m
2024-02-23 01:16:00,503 - INFO - [96mREFERENCES[95m	Allow to create a foreign key constraint.[0m
2024-02-23 01:16:00,503 - INFO - [96mSELECT    [95m	Allow to retrieve data from a table.[0m
2024-02-23 01:16:00,503 - INFO - [96mTRIGGER   [95m	Allow to create triggers on a table.[0m
2024-02-23 01:16:00,503 - INFO - [96mTRUNCATE  [95m	Allow to remove all rows from a table.[0m
2024-02-23 01:16:00,503 - INFO - [96mUPDATE    [95m	Allow to modify existing rows in a table.[0m
